##Linear Algebra 

In [1]:
import numpy as np

In [4]:
house = np.array([2,3,4])
print(house)
print(house.shape)

[2 3 4]
(3,)


##Matrix Operations 

In [5]:
A = np.array([
    [2, -1],
    [0, 3]
])
print(A.shape)

(2, 2)


In [7]:
B = np.array([
    [1, 2],
    [-3, 4]
])
print(B.shape)

(2, 2)


In [11]:
print("Adding the two matrices : ")
print(A + B)

Adding the two matrices : 
[[ 3  1]
 [-3  7]]


In [10]:
print("Dot Product: ")
print(A @ B)

Dot Product: 
[[ 5  0]
 [-9 12]]


In [13]:
print("Performing the \"3*A - 2*B\"")
print(3 * A - 2 * B)

Performing the "3*A - 2*B"
[[ 4 -7]
 [ 6  1]]


##Determminants and Inverse

In [20]:
import numpy.linalg as LA

In [25]:
print("Determinants of :")
print(A)
print("-"*10)
LA.det(A)

Determinants of :
[[ 2 -1]
 [ 0  3]]
----------


np.float64(6.0)

Here, the determinant of A is 6. Therefore, it is non-singular matrix and has its inverse.

In [30]:
print("Inverse of the matrix A :")
print(A)
print("-"*30)
print(LA.inv(A))

Inverse of the matrix A :
[[ 2 -1]
 [ 0  3]]
------------------------------
[[0.5        0.16666667]
 [0.         0.33333333]]


##Eigen Value and Eigen Vectors

In [32]:
C = np.array([
    [4, 1],
    [-2, 1]
])
print(C.shape)


(2, 2)


In [50]:
eigenvalues, eigenvectors = np.linalg.eig(C)

print("Eigen Values = ",eigenvalues[0])
print("Eigen Vectors : ")
print("First Eigen Vector: ",eigenvectors[:,0])
print("Second Eigen Vector: ",eigenvectors[:,1])

Eigen Values =  3.0
Eigen Vectors : 
First Eigen Vector:  [ 0.70710678 -0.70710678]
Second Eigen Vector:  [-0.4472136   0.89442719]


##Machine Learning

In [63]:
X = np.array([
    [4, 1.5, 100],
    [6, 2.0, 150]
])

y = np.array([20, 30])

In [69]:
beta = np.linalg.pinv(X) @ y

β=(X.T * X)^−1  X.T y, we don't use this beacuse normal inverse matrix doesn't exists means the shape of X matrix isnot square and singular matrix too. So the equation is X^-1 .y and we use "pinv" means pesudo-inverse done when the matrix isn't square matrix and not have sufficent values. 

In [70]:
car3 = np.array([8, 3.0, 200])

price = car3 @ beta 

In [73]:
print(" Car 3:")
print(car3)
print("Price of the car 3 is ",price)

 Car 3:
[  8.   3. 200.]
Price of the car 3 is  40.00000000000002
